# Generated by Django 4.2.23 on 2025-08-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_electronico', models.EmailField(max_length=254, verbose_name='e-mail')),
            ],
        ),
    ]
