# Generated by Django 4.2.23 on 2025-08-24 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f_c', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
