# Generated by Django 4.2.23 on 2025-08-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('f_c', '0002_delete_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_empresa', models.CharField(max_length=200, verbose_name='Empresa')),
                ('rut', models.IntegerField(verbose_name='RUT')),
                ('direccion', models.CharField(max_length=200, verbose_name='DIRECCION')),
                ('c_electronico', models.EmailField(max_length=254, verbose_name='e-mail')),
            ],
        ),
    ]
