# Generated by Django 4.2.23 on 2025-08-24 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f_c', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_pasajero', models.CharField(max_length=200, verbose_name='Nombre')),
                ('a_pasajero', models.CharField(max_length=200, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f_c.empresa')),
            ],
        ),
    ]
