# Generated by Django 4.2.23 on 2025-08-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_c', '0004_pasajero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_conductor', models.CharField(max_length=200, verbose_name='Nombre')),
                ('a_conductor', models.CharField(max_length=200, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=12, verbose_name='Telefono')),
            ],
        ),
    ]
