# Generated by Django 4.2.23 on 2025-08-24 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f_c', '0005_conductor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Viaje')),
                ('hora_salida_prog', models.TimeField(verbose_name='Hora de salida programada')),
                ('hora_salida_real', models.TimeField(blank=True, null=True, verbose_name='hora de salida real')),
                ('hora_llegada_prog', models.TimeField(verbose_name='Hora de llegada programada')),
                ('hora_llegada_real', models.TimeField(blank=True, null=True, verbose_name='Hora de llegada real')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f_c.conductor', verbose_name='Conductor')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f_c.empresa', verbose_name='Empresa')),
                ('pasajeros', models.ManyToManyField(related_name='viajes', to='f_c.pasajero', verbose_name='pasajeros')),
            ],
        ),
    ]
