# Generated by Django 4.2.23 on 2025-09-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_c', '0006_viaje'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductor',
            options={'verbose_name': 'Conductor', 'verbose_name_plural': 'Conducotres'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='pasajero',
            options={'verbose_name': 'Pasajero', 'verbose_name_plural': 'Pasajeros'},
        ),
        migrations.AlterModelOptions(
            name='viaje',
            options={'verbose_name': 'Viaje', 'verbose_name_plural': 'Viajes'},
        ),
        migrations.AlterField(
            model_name='empresa',
            name='c_electronico',
            field=models.EmailField(max_length=254, unique=True, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rut',
            field=models.IntegerField(unique=True, verbose_name='RUT'),
        ),
    ]
